apiVersion: v1 
kind: Secret
metadata:
  name: lesson-158-private
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository

stringData:
  url: git@github.com:amodh-2002/private-example-158.git
  sshPrivateKey: |
    
  insecure: "false"
  enableLfs: "true"